<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO');
$cfg_Cs[3]=array(1,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[4]=array(1,1,1,'5YWs5Y+45Y6G5Y+y');
$cfg_Cs[5]=array(0,1,1,'6IGU57O7');
$cfg_Cs[6]=array(0,17,1,'6LWE6K6v');
$cfg_Cs[7]=array(0,1,1,'6KeG6aKR5bGV56S6');
$cfg_Cs[8]=array(0,18,1,'55S75buKL+S6p+WTgQ==');
$cfg_Cs[9]=array(8,18,1,'5Lqn5ZOB5YiG57G75LiA');
$cfg_Cs[10]=array(0,17,1,'6aaW6aG16L2u55Wq5Zu+54mH');
?>