<div class="news-box"> <a href="[field:arcurl/]">
    <div class="news-list-img"><img src="[field:litpic/]"></div>
    </a>
    <div class="news-list-info">
      <div class="news-list-title"> <a href="[field:arcurl/]">
        <h4>[field:title/]</h4>
        </a>
        <p>[field:description function="cn_substr(@me,220)"/].... </p>
        <div class="news-more"><a href="[field:arcurl/]">继续阅读</a></div>
      </div>
    </div>
  </div>