<?php
$z[0]=Array("field","",174,197);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",241,271);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",308,335);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",370,402);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",1101,1136);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1222,1252);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n      <li class=\"sub-on\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n      ",1353,1495);
$z[6][4]['type']="son";
$z[6][4]['noself']="yes";
$z[7]=Array("field","",1573,1594);
$z[7][4]['name']="content";
$z[8]=Array("include","",1626,1661);
$z[8][4]['filename']="foot.htm";

?>