<?php
$z[0]=Array("field","",174,193);
$z[0][4]['name']="title";
$z[1]=Array("global","",237,267);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",304,331);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",413,445);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",1144,1179);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1265,1284);
$z[5][4]['name']="title";
$z[6]=Array("type","<a class=\"btn-back\" href=\"[field:typelink /] \"></a>",1318,1409);
$z[6][4]['typeid']="0";
$z[6][4]['row']="1";
$z[7]=Array("prenext","preg_match_all('/<a.*?(?: |\\\\t|\\\\r|\\\\n)?href=[\\'\"]?(.+?)[\\'\"]?(?:(?: |\\\\t|\\\\r|\\\\n)+.*?)?>(.+?)<\\/a.*?>/sim', @me, \$strResult, PREG_PATTERN_ORDER);@me=\$strResult[1][0];",1437,1656);
$z[7][4]['get']="pro";
$z[7][4]['runphp']="yes";
$z[8]=Array("prenext","preg_match_all('/<a.*?(?: |\\\\t|\\\\r|\\\\n)?href=[\\'\"]?(.+?)[\\'\"]?(?:(?: |\\\\t|\\\\r|\\\\n)+.*?)?>(.+?)<\\/a.*?>/sim', @me, \$strResult, PREG_PATTERN_ORDER);@me=\$strResult[1][0];",1690,1910);
$z[8][4]['get']="next";
$z[8][4]['runphp']="yes";
$z[9]=Array("field","",1961,1981);
$z[9][4]['name']="litpic";
$z[10]=Array("field","",1999,2019);
$z[10][4]['name']="cpxxjs";
$z[11]=Array("include","",2043,2078);
$z[11][4]['filename']="foot.htm";

?>