<?php
$z[0]=Array("global","",65,97);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("field","(@me==\"\")? @me=\" class='on' \":@me=\"\";",235,322);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channel","\r\n      <li><a href=\"[field:typeurl/]\" target=\"_self\">[field:typename/]</a></li>\r\n      ",374,607);
$z[2][4]['type']="top";
$z[2][4]['currentstyle']="<li class='on'><a href='~typelink~' class='thisclass'>~typename~</a></li>";

?>