<?php
$z[0]=Array("global","",174,200);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",244,274);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",311,338);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",476,508);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",1215,1250);
$z[4][4]['filename']="head.htm";
$z[5]=Array("arclist","\r\n    <li style=\"width: 1200px; height: 500px; \"><a ><img alt=\"[field:title/]\" src=\"[field:litpic/]\" style=\"width: 1200px; \"></a></li>\r\n    ",1367,1572);
$z[5][4]['row']="8";
$z[5][4]['typeid']="10";
$z[5][4]['titlelen']="58";
$z[6]=Array("global","",1756,1781);
$z[6][4]['name']="index_gsjj";
$z[7]=Array("arclist"," <a href=\"[field:arcurl/]\">\r\n  <div class=\"pic-box\"> <img src=\"[field:litpic/]\" width=\"286\" height=\"190\">\r\n    <div class=\"box-over\"></div>\r\n    <p>[field:title/]</p>\r\n  </div>\r\n  </a> ",1865,2114);
$z[7][4]['row']="8";
$z[7][4]['typeid']="8";
$z[7][4]['titlelen']="58";
$z[8]=Array("arclist","\r\n  <div class=\"news-box\"> <a href=\"[field:arcurl/]\">\r\n    <div class=\"news-list-img\"><img src=\"[field:litpic/]\"></div>\r\n    </a>\r\n    <div class=\"news-list-info\">\r\n      <div class=\"news-list-title\"> <a href=\"[field:arcurl/]\">\r\n        <h4>[field:title/]</h4>\r\n        </a>\r\n        <p>[field:description function=\"cn_substr(@me,220)\"/].... </p>\r\n        <div class=\"news-more\"><a href=\"[field:arcurl/]\">继续阅读</a></div>\r\n      </div>\r\n    </div>\r\n  </div>\r\n  ",2199,2730);
$z[8][4]['row']="2";
$z[8][4]['typeid']="6";
$z[8][4]['titlelen']="58";
$z[9]=Array("include","",2739,2774);
$z[9][4]['filename']="foot.htm";

?>