<?php
$z[0]=Array("field","",174,197);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",241,271);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",308,335);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",417,449);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",1148,1183);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1303,1333);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n      <li class=\"sub-on\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n      ",1356,1498);
$z[6][4]['type']="son";
$z[6][4]['noself']="yes";
$z[7]=Array("list"," <a href=\"[field:arcurl/]\">\r\n    <div class=\"pic-box\"> <img src=\"[field:litpic/]\" width=\"285\" height=\"190\">\r\n      <div class=\"box-over\"></div>\r\n      <p>[field:title/]</p>\r\n    </div>\r\n    </a> ",1545,1791);
$z[7][4]['pagesize']="8";
$z[7][4]['titlelen']="60";
$z[8]=Array("pagelist","",1858,1929);
$z[8][4]['listitem']="info,index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",1966,2001);
$z[9][4]['filename']="foot.htm";

?>