<?php
$z[0]=Array("field","",174,197);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",241,271);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",308,335);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",417,449);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",1148,1183);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1252,1282);
$z[5][4]['name']="typename";
$z[6]=Array("list","\r\n  <div class=\"news-box\"> <a href=\"[field:arcurl/]\">\r\n    <div class=\"news-list-img\"><img src=\"[field:litpic/]\"></div>\r\n    </a>\r\n    <div class=\"news-list-info\">\r\n      <div class=\"news-list-title\"> <a href=\"[field:arcurl/]\">\r\n        <h4>[field:title/]</h4>\r\n        </a>\r\n        <p>[field:description function=\"cn_substr(@me,255)\"/]… </p>\r\n        <div class=\"news-more\"><a href=\"[field:arcurl/]\">继续阅读</a></div>\r\n      </div>\r\n    </div>\r\n  </div>\r\n  ",1338,1855);
$z[6][4]['pagesize']="8";
$z[6][4]['titlelen']="60";
$z[7]=Array("pagelist","",1916,1987);
$z[7][4]['listitem']="info,index,end,pre,next,pageno";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",2012,2047);
$z[8][4]['filename']="foot.htm";

?>